resolver: nightly-2018-10-03
packages:
- .

extra-deps:
- asn1-encoding-0.9.5
- asn1-parse-0.9.4
- asn1-types-0.3.2
- byteable-0.1.1
- connection-0.2.8
- containers-0.5.11.0
- cryptonite-0.25
- exception-mtl-0.4.0.1
- exception-transformers-0.4.0.7
- happy-1.19.9
- haskell-src-meta-0.8.0.3
- http-client-0.5.13.1
- http-client-tls-0.3.5.3
- http-conduit-2.3.2
- json-0.9.2
- language-c-quote-0.12.2
- mainland-pretty-0.7
- megaparsec-7.0.1
- neat-interpolation-0.3.2.4
- pem-0.2.4
- srcloc-0.5.1.2
- symbol-0.2.4
- tls-1.4.1
- vector-binary-instances-0.2.5
- versions-3.5.0
- x509-1.7.4
- x509-store-1.6.6
- x509-system-1.6.6
- x509-validation-1.6.10
flags: {}

extra-package-dbs: []

allow-newer: true # XXX
